services:
  redbot:
    image: ghcr.io/moldytaint/red-discord-bot-docker:latest
    volumes:
      - redbot_data:/app/data
      - redbot_audio:/app/data/audio_cache  # Separate volume for audio cache
    env_file:
      - .env
    restart: unless-stopped
    # Resource limits to prevent memory/CPU issues
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    # Improved healthcheck to properly detect bot status
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -v grep | grep -q redbot || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Security options
    security_opt:
      - no-new-privileges:true
    # Additional host configuration
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0  # Enable IPv6 for better connectivity
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - redbot_network

  # Optional Lavalink service (uncomment to use)
  # lavalink:
  #   image: fredboat/lavalink:latest
  #   volumes:
  #     - ./lavalink-application.yml:/opt/Lavalink/application.yml
  #   networks:
  #     - redbot_network
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #       reservations:
  #         memory: 256M
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:2333/version || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 15s

volumes:
  redbot_data:
    name: redbot_data
  redbot_audio:
    name: redbot_audio

networks:
  redbot_network:
    name: redbot_network
